### ISSUE TITLE
Compatibility to larger scale point clouds

### ISSUE THREAD

**Issue by gitouni** [JoeyforJoy/Eigen-Based-KD-Tree#2]
Thanks for sharing this useful and advanced repo. I'm concered about using `int` in point_idx will cause memory overflow error when the input point cloud is too large (such as KITTI, almsot 10k points).

Please see [here](https://github.com/YuanxianH/Eigen-Based-KD-Tree/blob/master/src/kdtree.hpp#:~:text=std%3A%3Avector%3Cint%3E%20points_idx%3B)

I think replacing `int` with `std::size_t` would be better.

**Comment by YuanxianH** [comment]
Well, thank you for your valuable suggestion. `std::size_t` does be better for its platform adaptability. I will modify it later.

**Comment by YuanxianH** [comment]
> Well, thank you for your valuable suggestion. `std::size_t` does be better for its platform adaptability. I will modify it later.

I have modified it in the new commit. Feel free for any questions.
